# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'list_edit.ui'
#
# Created by: PyQt5 UI code generator 5.7.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_EditPubList(object):
    def setupUi(self, EditPubList):
        EditPubList.setObjectName("EditPubList")
        EditPubList.resize(505, 575)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(EditPubList)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pub_list = QtWidgets.QListWidget(EditPubList)
        self.pub_list.setMaximumSize(QtCore.QSize(200, 16777215))
        self.pub_list.setObjectName("pub_list")
        self.horizontalLayout_3.addWidget(self.pub_list)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.groupBox = QtWidgets.QGroupBox(EditPubList)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.pub_name = QtWidgets.QLineEdit(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pub_name.setFont(font)
        self.pub_name.setObjectName("pub_name")
        self.horizontalLayout.addWidget(self.pub_name)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.btn_add = QtWidgets.QPushButton(self.groupBox)
        self.btn_add.setObjectName("btn_add")
        self.verticalLayout.addWidget(self.btn_add)
        self.verticalLayout_3.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(EditPubList)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 35))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.newname_box = QtWidgets.QLineEdit(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.newname_box.setFont(font)
        self.newname_box.setObjectName("newname_box")
        self.gridLayout.addWidget(self.newname_box, 1, 1, 1, 1)
        self.lbl_current_name = QtWidgets.QLabel(self.groupBox_2)
        self.lbl_current_name.setMaximumSize(QtCore.QSize(16777215, 35))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lbl_current_name.setFont(font)
        self.lbl_current_name.setObjectName("lbl_current_name")
        self.gridLayout.addWidget(self.lbl_current_name, 0, 1, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout)
        self.btn_update = QtWidgets.QPushButton(self.groupBox_2)
        self.btn_update.setObjectName("btn_update")
        self.verticalLayout_2.addWidget(self.btn_update)
        self.verticalLayout_3.addWidget(self.groupBox_2)
        self.groupBox_3 = QtWidgets.QGroupBox(EditPubList)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_4 = QtWidgets.QLabel(self.groupBox_3)
        self.label_4.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        self.lbl_del_name = QtWidgets.QLabel(self.groupBox_3)
        self.lbl_del_name.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lbl_del_name.setFont(font)
        self.lbl_del_name.setObjectName("lbl_del_name")
        self.horizontalLayout_4.addWidget(self.lbl_del_name)
        self.verticalLayout_5.addLayout(self.horizontalLayout_4)
        self.btn_remove = QtWidgets.QPushButton(self.groupBox_3)
        self.btn_remove.setObjectName("btn_remove")
        self.verticalLayout_5.addWidget(self.btn_remove)
        self.verticalLayout_3.addWidget(self.groupBox_3)
        self.horizontalLayout_3.addLayout(self.verticalLayout_3)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.btn_close = QtWidgets.QPushButton(EditPubList)
        self.btn_close.setMinimumSize(QtCore.QSize(150, 50))
        self.btn_close.setObjectName("btn_close")
        self.horizontalLayout_2.addWidget(self.btn_close)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)

        self.retranslateUi(EditPubList)
        QtCore.QMetaObject.connectSlotsByName(EditPubList)

    def retranslateUi(self, EditPubList):
        _translate = QtCore.QCoreApplication.translate
        EditPubList.setWindowTitle(_translate("EditPubList", "Edit Publisher List"))
        self.groupBox.setTitle(_translate("EditPubList", "Add Publisher"))
        self.label.setText(_translate("EditPubList", "Name:"))
        self.btn_add.setText(_translate("EditPubList", "Add name to list."))
        self.groupBox_2.setTitle(_translate("EditPubList", "Edit Publisher"))
        self.label_2.setText(_translate("EditPubList", "Current Name:"))
        self.label_3.setText(_translate("EditPubList", "New Name:"))
        self.lbl_current_name.setText(_translate("EditPubList", "Publisher Name"))
        self.btn_update.setText(_translate("EditPubList", "Update publisher name."))
        self.groupBox_3.setTitle(_translate("EditPubList", "Remove Publisher"))
        self.label_4.setText(_translate("EditPubList", "Name:"))
        self.lbl_del_name.setText(_translate("EditPubList", "Publisher Name"))
        self.btn_remove.setText(_translate("EditPubList", "Delete selected name and talk history from list."))
        self.btn_close.setText(_translate("EditPubList", "Close"))

