# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'scheduler.ui'
#
# Created by: PyQt5 UI code generator 5.7.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(952, 688)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.rdo_sort_days = QtWidgets.QRadioButton(self.centralwidget)
        self.rdo_sort_days.setChecked(True)
        self.rdo_sort_days.setObjectName("rdo_sort_days")
        self.verticalLayout_2.addWidget(self.rdo_sort_days)
        self.rdo_sort_lah = QtWidgets.QRadioButton(self.centralwidget)
        self.rdo_sort_lah.setObjectName("rdo_sort_lah")
        self.verticalLayout_2.addWidget(self.rdo_sort_lah)
        self.publisher_listbox = QtWidgets.QListWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.publisher_listbox.sizePolicy().hasHeightForWidth())
        self.publisher_listbox.setSizePolicy(sizePolicy)
        self.publisher_listbox.setMaximumSize(QtCore.QSize(200, 16777215))
        self.publisher_listbox.setObjectName("publisher_listbox")
        self.verticalLayout_2.addWidget(self.publisher_listbox)
        self.lbl_total_pubs = QtWidgets.QLabel(self.centralwidget)
        self.lbl_total_pubs.setObjectName("lbl_total_pubs")
        self.verticalLayout_2.addWidget(self.lbl_total_pubs)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.contents = QtWidgets.QVBoxLayout()
        self.contents.setObjectName("contents")
        self.pubhistory_sched = QtWidgets.QHBoxLayout()
        self.pubhistory_sched.setObjectName("pubhistory_sched")
        self.pub_history = QtWidgets.QGroupBox(self.centralwidget)
        self.pub_history.setObjectName("pub_history")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.pub_history)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.lbl_pub_name = QtWidgets.QLabel(self.pub_history)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_pub_name.setFont(font)
        self.lbl_pub_name.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.lbl_pub_name.setObjectName("lbl_pub_name")
        self.verticalLayout_5.addWidget(self.lbl_pub_name)
        self.hist_contents = QtWidgets.QHBoxLayout()
        self.hist_contents.setObjectName("hist_contents")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.pub_history)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_3.addWidget(self.label_2)
        self.pub_hist_listbox = QtWidgets.QListWidget(self.pub_history)
        self.pub_hist_listbox.setMaximumSize(QtCore.QSize(191, 16777215))
        self.pub_hist_listbox.setObjectName("pub_hist_listbox")
        self.verticalLayout_3.addWidget(self.pub_hist_listbox)
        self.hist_contents.addLayout(self.verticalLayout_3)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.lbl_next_part = QtWidgets.QLabel(self.pub_history)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lbl_next_part.setFont(font)
        self.lbl_next_part.setObjectName("lbl_next_part")
        self.gridLayout_2.addWidget(self.lbl_next_part, 6, 1, 1, 1)
        self.label_26 = QtWidgets.QLabel(self.pub_history)
        self.label_26.setMinimumSize(QtCore.QSize(0, 27))
        self.label_26.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_26.setFont(font)
        self.label_26.setObjectName("label_26")
        self.gridLayout_2.addWidget(self.label_26, 4, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 10, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem1, 10, 0, 1, 1)
        self.label_24 = QtWidgets.QLabel(self.pub_history)
        self.label_24.setMinimumSize(QtCore.QSize(0, 27))
        self.label_24.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_24.setFont(font)
        self.label_24.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_24.setObjectName("label_24")
        self.gridLayout_2.addWidget(self.label_24, 3, 0, 1, 1)
        self.label_25 = QtWidgets.QLabel(self.pub_history)
        self.label_25.setMinimumSize(QtCore.QSize(0, 27))
        self.label_25.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_25.setFont(font)
        self.label_25.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_25.setObjectName("label_25")
        self.gridLayout_2.addWidget(self.label_25, 7, 0, 1, 1)
        self.lbl_last_as_household = QtWidgets.QLabel(self.pub_history)
        self.lbl_last_as_household.setMinimumSize(QtCore.QSize(0, 27))
        self.lbl_last_as_household.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lbl_last_as_household.setFont(font)
        self.lbl_last_as_household.setObjectName("lbl_last_as_household")
        self.gridLayout_2.addWidget(self.lbl_last_as_household, 4, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.pub_history)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 2, 0, 1, 1)
        self.lbl_next_talk = QtWidgets.QLabel(self.pub_history)
        self.lbl_next_talk.setMinimumSize(QtCore.QSize(0, 27))
        self.lbl_next_talk.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lbl_next_talk.setFont(font)
        self.lbl_next_talk.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.lbl_next_talk.setObjectName("lbl_next_talk")
        self.gridLayout_2.addWidget(self.lbl_next_talk, 5, 1, 1, 1)
        self.lbl_last_part = QtWidgets.QLabel(self.pub_history)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lbl_last_part.setFont(font)
        self.lbl_last_part.setObjectName("lbl_last_part")
        self.gridLayout_2.addWidget(self.lbl_last_part, 2, 1, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.pub_history)
        self.label_23.setMinimumSize(QtCore.QSize(0, 27))
        self.label_23.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_23.setFont(font)
        self.label_23.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_23.setObjectName("label_23")
        self.gridLayout_2.addWidget(self.label_23, 1, 0, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.pub_history)
        self.label_22.setMinimumSize(QtCore.QSize(0, 27))
        self.label_22.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_22.setFont(font)
        self.label_22.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_22.setObjectName("label_22")
        self.gridLayout_2.addWidget(self.label_22, 5, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.pub_history)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 9, 0, 1, 1)
        self.lbl_last_talk = QtWidgets.QLabel(self.pub_history)
        self.lbl_last_talk.setMinimumSize(QtCore.QSize(0, 27))
        self.lbl_last_talk.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lbl_last_talk.setFont(font)
        self.lbl_last_talk.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.lbl_last_talk.setObjectName("lbl_last_talk")
        self.gridLayout_2.addWidget(self.lbl_last_talk, 1, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.pub_history)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 6, 0, 1, 1)
        self.lbl_last_council = QtWidgets.QLabel(self.pub_history)
        self.lbl_last_council.setMinimumSize(QtCore.QSize(0, 27))
        self.lbl_last_council.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lbl_last_council.setFont(font)
        self.lbl_last_council.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.lbl_last_council.setObjectName("lbl_last_council")
        self.gridLayout_2.addWidget(self.lbl_last_council, 3, 1, 1, 1)
        self.freq_box = QtWidgets.QComboBox(self.pub_history)
        self.freq_box.setMinimumSize(QtCore.QSize(0, 27))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.freq_box.setFont(font)
        self.freq_box.setObjectName("freq_box")
        self.freq_box.addItem("")
        self.freq_box.addItem("")
        self.freq_box.addItem("")
        self.freq_box.addItem("")
        self.freq_box.addItem("")
        self.gridLayout_2.addWidget(self.freq_box, 9, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.pub_history)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 8, 0, 1, 1)
        self.next_council_box = QtWidgets.QComboBox(self.pub_history)
        self.next_council_box.setMinimumSize(QtCore.QSize(0, 27))
        self.next_council_box.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.next_council_box.setFont(font)
        self.next_council_box.setObjectName("next_council_box")
        self.next_council_box.addItem("")
        self.next_council_box.addItem("")
        self.next_council_box.addItem("")
        self.next_council_box.addItem("")
        self.next_council_box.addItem("")
        self.next_council_box.addItem("")
        self.next_council_box.addItem("")
        self.next_council_box.addItem("")
        self.next_council_box.addItem("")
        self.next_council_box.addItem("")
        self.next_council_box.addItem("")
        self.next_council_box.addItem("")
        self.next_council_box.addItem("")
        self.next_council_box.addItem("")
        self.next_council_box.addItem("")
        self.next_council_box.addItem("")
        self.next_council_box.addItem("")
        self.next_council_box.addItem("")
        self.next_council_box.addItem("")
        self.next_council_box.addItem("")
        self.next_council_box.addItem("")
        self.next_council_box.addItem("")
        self.next_council_box.addItem("")
        self.next_council_box.addItem("")
        self.next_council_box.addItem("")
        self.next_council_box.addItem("")
        self.next_council_box.addItem("")
        self.next_council_box.addItem("")
        self.next_council_box.addItem("")
        self.next_council_box.addItem("")
        self.next_council_box.addItem("")
        self.next_council_box.addItem("")
        self.next_council_box.addItem("")
        self.next_council_box.addItem("")
        self.next_council_box.addItem("")
        self.next_council_box.addItem("")
        self.next_council_box.addItem("")
        self.next_council_box.addItem("")
        self.next_council_box.addItem("")
        self.next_council_box.addItem("")
        self.next_council_box.addItem("")
        self.next_council_box.addItem("")
        self.next_council_box.addItem("")
        self.next_council_box.addItem("")
        self.next_council_box.addItem("")
        self.next_council_box.addItem("")
        self.next_council_box.addItem("")
        self.next_council_box.addItem("")
        self.next_council_box.addItem("")
        self.next_council_box.addItem("")
        self.next_council_box.addItem("")
        self.next_council_box.addItem("")
        self.next_council_box.addItem("")
        self.next_council_box.addItem("")
        self.gridLayout_2.addWidget(self.next_council_box, 8, 1, 1, 1)
        self.lbl_next_council = QtWidgets.QLabel(self.pub_history)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lbl_next_council.setFont(font)
        self.lbl_next_council.setObjectName("lbl_next_council")
        self.gridLayout_2.addWidget(self.lbl_next_council, 7, 1, 1, 1)
        self.hist_contents.addLayout(self.gridLayout_2)
        self.verticalLayout_5.addLayout(self.hist_contents)
        self.pubhistory_sched.addWidget(self.pub_history)
        self.schedule = QtWidgets.QGroupBox(self.centralwidget)
        self.schedule.setMaximumSize(QtCore.QSize(160, 16777215))
        self.schedule.setObjectName("schedule")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.schedule)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.year_box = QtWidgets.QComboBox(self.schedule)
        self.year_box.setObjectName("year_box")
        self.verticalLayout_4.addWidget(self.year_box)
        self.schedule_listbox = QtWidgets.QListWidget(self.schedule)
        self.schedule_listbox.setMaximumSize(QtCore.QSize(150, 16777215))
        self.schedule_listbox.setObjectName("schedule_listbox")
        self.verticalLayout_4.addWidget(self.schedule_listbox)
        self.chk_slips_printed = QtWidgets.QCheckBox(self.schedule)
        self.chk_slips_printed.setObjectName("chk_slips_printed")
        self.verticalLayout_4.addWidget(self.chk_slips_printed)
        self.pubhistory_sched.addWidget(self.schedule)
        self.contents.addLayout(self.pubhistory_sched)
        self.mtg_parts = QtWidgets.QGroupBox(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.mtg_parts.setFont(font)
        self.mtg_parts.setObjectName("mtg_parts")
        self.gridLayout = QtWidgets.QGridLayout(self.mtg_parts)
        self.gridLayout.setObjectName("gridLayout")
        self.lbl_rv_hhold_pub = QtWidgets.QLabel(self.mtg_parts)
        self.lbl_rv_hhold_pub.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.lbl_rv_hhold_pub.setObjectName("lbl_rv_hhold_pub")
        self.gridLayout.addWidget(self.lbl_rv_hhold_pub, 5, 2, 1, 1)
        self.lbl_hhold = QtWidgets.QLabel(self.mtg_parts)
        self.lbl_hhold.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.lbl_hhold.setObjectName("lbl_hhold")
        self.gridLayout.addWidget(self.lbl_hhold, 7, 1, 1, 1)
        self.assign_bs = QtWidgets.QPushButton(self.mtg_parts)
        self.assign_bs.setMaximumSize(QtCore.QSize(49, 16777215))
        self.assign_bs.setObjectName("assign_bs")
        self.gridLayout.addWidget(self.assign_bs, 6, 4, 1, 1)
        self.assign_rvh = QtWidgets.QPushButton(self.mtg_parts)
        self.assign_rvh.setMaximumSize(QtCore.QSize(49, 16777215))
        self.assign_rvh.setObjectName("assign_rvh")
        self.gridLayout.addWidget(self.assign_rvh, 5, 4, 1, 1)
        self.lbl_bs_cou = QtWidgets.QLabel(self.mtg_parts)
        self.lbl_bs_cou.setMaximumSize(QtCore.QSize(47, 16777215))
        self.lbl_bs_cou.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.lbl_bs_cou.setObjectName("lbl_bs_cou")
        self.gridLayout.addWidget(self.lbl_bs_cou, 6, 3, 1, 1)
        self.assign_bsh = QtWidgets.QPushButton(self.mtg_parts)
        self.assign_bsh.setMaximumSize(QtCore.QSize(49, 16777215))
        self.assign_bsh.setObjectName("assign_bsh")
        self.gridLayout.addWidget(self.assign_bsh, 7, 4, 1, 1)
        self.lbl_bs_pub = QtWidgets.QLabel(self.mtg_parts)
        self.lbl_bs_pub.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.lbl_bs_pub.setObjectName("lbl_bs_pub")
        self.gridLayout.addWidget(self.lbl_bs_pub, 6, 2, 1, 1)
        self.lbl_bs = QtWidgets.QLabel(self.mtg_parts)
        self.lbl_bs.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.lbl_bs.setObjectName("lbl_bs")
        self.gridLayout.addWidget(self.lbl_bs, 6, 1, 1, 1)
        self.lbl_bs_hhold_pub = QtWidgets.QLabel(self.mtg_parts)
        self.lbl_bs_hhold_pub.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.lbl_bs_hhold_pub.setObjectName("lbl_bs_hhold_pub")
        self.gridLayout.addWidget(self.lbl_bs_hhold_pub, 7, 2, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.mtg_parts)
        self.label_18.setMaximumSize(QtCore.QSize(47, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_18.setFont(font)
        self.label_18.setAlignment(QtCore.Qt.AlignCenter)
        self.label_18.setObjectName("label_18")
        self.gridLayout.addWidget(self.label_18, 0, 3, 1, 1)
        self.lbl_fv = QtWidgets.QLabel(self.mtg_parts)
        self.lbl_fv.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.lbl_fv.setObjectName("lbl_fv")
        self.gridLayout.addWidget(self.lbl_fv, 2, 1, 1, 1)
        self.lbl_fv_pub = QtWidgets.QLabel(self.mtg_parts)
        self.lbl_fv_pub.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.lbl_fv_pub.setObjectName("lbl_fv_pub")
        self.gridLayout.addWidget(self.lbl_fv_pub, 2, 2, 1, 1)
        self.lbl_read_cou = QtWidgets.QLabel(self.mtg_parts)
        self.lbl_read_cou.setMaximumSize(QtCore.QSize(47, 16777215))
        self.lbl_read_cou.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_read_cou.setObjectName("lbl_read_cou")
        self.gridLayout.addWidget(self.lbl_read_cou, 1, 3, 1, 1)
        self.assign_fv = QtWidgets.QPushButton(self.mtg_parts)
        self.assign_fv.setMaximumSize(QtCore.QSize(49, 16777215))
        self.assign_fv.setObjectName("assign_fv")
        self.gridLayout.addWidget(self.assign_fv, 2, 4, 1, 1)
        self.lbl_read_pub = QtWidgets.QLabel(self.mtg_parts)
        self.lbl_read_pub.setObjectName("lbl_read_pub")
        self.gridLayout.addWidget(self.lbl_read_pub, 1, 2, 1, 1)
        self.assign_reading = QtWidgets.QPushButton(self.mtg_parts)
        self.assign_reading.setMaximumSize(QtCore.QSize(49, 16777215))
        self.assign_reading.setObjectName("assign_reading")
        self.gridLayout.addWidget(self.assign_reading, 1, 4, 1, 1)
        self.lbl_fv_cou = QtWidgets.QLabel(self.mtg_parts)
        self.lbl_fv_cou.setMaximumSize(QtCore.QSize(47, 16777215))
        self.lbl_fv_cou.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.lbl_fv_cou.setObjectName("lbl_fv_cou")
        self.gridLayout.addWidget(self.lbl_fv_cou, 2, 3, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.mtg_parts)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_15.setObjectName("label_15")
        self.gridLayout.addWidget(self.label_15, 0, 1, 1, 1)
        self.lbl_fv_hhold = QtWidgets.QLabel(self.mtg_parts)
        self.lbl_fv_hhold.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.lbl_fv_hhold.setObjectName("lbl_fv_hhold")
        self.gridLayout.addWidget(self.lbl_fv_hhold, 3, 1, 1, 1)
        self.lvl_rv = QtWidgets.QLabel(self.mtg_parts)
        self.lvl_rv.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.lvl_rv.setObjectName("lvl_rv")
        self.gridLayout.addWidget(self.lvl_rv, 4, 1, 1, 1)
        self.lbl_rv_cou = QtWidgets.QLabel(self.mtg_parts)
        self.lbl_rv_cou.setMaximumSize(QtCore.QSize(47, 16777215))
        self.lbl_rv_cou.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.lbl_rv_cou.setObjectName("lbl_rv_cou")
        self.gridLayout.addWidget(self.lbl_rv_cou, 4, 3, 1, 1)
        self.assign_rv = QtWidgets.QPushButton(self.mtg_parts)
        self.assign_rv.setMaximumSize(QtCore.QSize(49, 16777215))
        self.assign_rv.setObjectName("assign_rv")
        self.gridLayout.addWidget(self.assign_rv, 4, 4, 1, 1)
        self.lvl_rv_hhold = QtWidgets.QLabel(self.mtg_parts)
        self.lvl_rv_hhold.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.lvl_rv_hhold.setObjectName("lvl_rv_hhold")
        self.gridLayout.addWidget(self.lvl_rv_hhold, 5, 1, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.mtg_parts)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_17.setFont(font)
        self.label_17.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_17.setObjectName("label_17")
        self.gridLayout.addWidget(self.label_17, 0, 2, 1, 1)
        self.lbl_read = QtWidgets.QLabel(self.mtg_parts)
        self.lbl_read.setObjectName("lbl_read")
        self.gridLayout.addWidget(self.lbl_read, 1, 1, 1, 1)
        self.lbl_fv_hhold_pub = QtWidgets.QLabel(self.mtg_parts)
        self.lbl_fv_hhold_pub.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.lbl_fv_hhold_pub.setObjectName("lbl_fv_hhold_pub")
        self.gridLayout.addWidget(self.lbl_fv_hhold_pub, 3, 2, 1, 1)
        self.assign_fvh = QtWidgets.QPushButton(self.mtg_parts)
        self.assign_fvh.setMaximumSize(QtCore.QSize(49, 16777215))
        self.assign_fvh.setObjectName("assign_fvh")
        self.gridLayout.addWidget(self.assign_fvh, 3, 4, 1, 1)
        self.lbl_rv_pub = QtWidgets.QLabel(self.mtg_parts)
        self.lbl_rv_pub.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.lbl_rv_pub.setObjectName("lbl_rv_pub")
        self.gridLayout.addWidget(self.lbl_rv_pub, 4, 2, 1, 1)
        self.chk_read_cancel = QtWidgets.QCheckBox(self.mtg_parts)
        self.chk_read_cancel.setMaximumSize(QtCore.QSize(48, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.chk_read_cancel.setFont(font)
        self.chk_read_cancel.setText("")
        self.chk_read_cancel.setObjectName("chk_read_cancel")
        self.gridLayout.addWidget(self.chk_read_cancel, 1, 0, 1, 1)
        self.chk_fv_cancel = QtWidgets.QCheckBox(self.mtg_parts)
        self.chk_fv_cancel.setMaximumSize(QtCore.QSize(48, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.chk_fv_cancel.setFont(font)
        self.chk_fv_cancel.setText("")
        self.chk_fv_cancel.setObjectName("chk_fv_cancel")
        self.gridLayout.addWidget(self.chk_fv_cancel, 2, 0, 1, 1)
        self.chk_rv_cancel = QtWidgets.QCheckBox(self.mtg_parts)
        self.chk_rv_cancel.setMaximumSize(QtCore.QSize(48, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.chk_rv_cancel.setFont(font)
        self.chk_rv_cancel.setText("")
        self.chk_rv_cancel.setObjectName("chk_rv_cancel")
        self.gridLayout.addWidget(self.chk_rv_cancel, 4, 0, 1, 1)
        self.chk_bs_cancel = QtWidgets.QCheckBox(self.mtg_parts)
        self.chk_bs_cancel.setMaximumSize(QtCore.QSize(48, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.chk_bs_cancel.setFont(font)
        self.chk_bs_cancel.setText("")
        self.chk_bs_cancel.setObjectName("chk_bs_cancel")
        self.gridLayout.addWidget(self.chk_bs_cancel, 6, 0, 1, 1)
        self.label_28 = QtWidgets.QLabel(self.mtg_parts)
        self.label_28.setMaximumSize(QtCore.QSize(48, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_28.setFont(font)
        self.label_28.setObjectName("label_28")
        self.gridLayout.addWidget(self.label_28, 0, 0, 1, 1)
        self.chk_fvh_cancel = QtWidgets.QCheckBox(self.mtg_parts)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.chk_fvh_cancel.setFont(font)
        self.chk_fvh_cancel.setText("")
        self.chk_fvh_cancel.setObjectName("chk_fvh_cancel")
        self.gridLayout.addWidget(self.chk_fvh_cancel, 3, 0, 1, 1)
        self.chk_rvh_cancel = QtWidgets.QCheckBox(self.mtg_parts)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.chk_rvh_cancel.setFont(font)
        self.chk_rvh_cancel.setText("")
        self.chk_rvh_cancel.setObjectName("chk_rvh_cancel")
        self.gridLayout.addWidget(self.chk_rvh_cancel, 5, 0, 1, 1)
        self.chk_bsh_cancel = QtWidgets.QCheckBox(self.mtg_parts)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.chk_bsh_cancel.setFont(font)
        self.chk_bsh_cancel.setText("")
        self.chk_bsh_cancel.setObjectName("chk_bsh_cancel")
        self.gridLayout.addWidget(self.chk_bsh_cancel, 7, 0, 1, 1)
        self.contents.addWidget(self.mtg_parts)
        self.horizontalLayout.addLayout(self.contents)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.btn_edit_list = QtWidgets.QPushButton(self.centralwidget)
        self.btn_edit_list.setObjectName("btn_edit_list")
        self.horizontalLayout_3.addWidget(self.btn_edit_list)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.btn_close = QtWidgets.QPushButton(self.centralwidget)
        self.btn_close.setObjectName("btn_close")
        self.horizontalLayout_3.addWidget(self.btn_close)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 952, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.freq_box.setCurrentIndex(1)
        self.chk_read_cancel.toggled['bool'].connect(self.assign_reading.setDisabled)
        self.chk_fv_cancel.toggled['bool'].connect(self.assign_fv.setDisabled)
        self.chk_fvh_cancel.toggled['bool'].connect(self.assign_fvh.setDisabled)
        self.chk_rv_cancel.toggled['bool'].connect(self.assign_rv.setDisabled)
        self.chk_rvh_cancel.toggled['bool'].connect(self.assign_rvh.setDisabled)
        self.chk_bs_cancel.toggled['bool'].connect(self.assign_bs.setDisabled)
        self.chk_bsh_cancel.toggled['bool'].connect(self.assign_bsh.setDisabled)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "School Scheduler"))
        self.rdo_sort_days.setText(_translate("MainWindow", "Sort by days since last talk given"))
        self.rdo_sort_lah.setText(_translate("MainWindow", "Sort by last time as householder"))
        self.lbl_total_pubs.setText(_translate("MainWindow", "Total publisher count:"))
        self.pub_history.setTitle(_translate("MainWindow", "Publisher History"))
        self.lbl_pub_name.setText(_translate("MainWindow", "Publisher Name"))
        self.label_2.setText(_translate("MainWindow", "Talk Date - Part Given (Council)"))
        self.lbl_next_part.setText(_translate("MainWindow", "Part"))
        self.label_26.setText(_translate("MainWindow", "Last as householder:"))
        self.label_24.setText(_translate("MainWindow", "Last council:"))
        self.label_25.setText(_translate("MainWindow", "Next council:"))
        self.lbl_last_as_household.setText(_translate("MainWindow", "Month and Day"))
        self.label.setText(_translate("MainWindow", "Last part:"))
        self.lbl_next_talk.setText(_translate("MainWindow", "Month and Day"))
        self.lbl_last_part.setText(_translate("MainWindow", "Part"))
        self.label_23.setText(_translate("MainWindow", "Last talk date:"))
        self.label_22.setText(_translate("MainWindow", "Next talk date:"))
        self.label_4.setText(_translate("MainWindow", "Talk frequency:"))
        self.lbl_last_talk.setText(_translate("MainWindow", "Month and Day"))
        self.label_3.setText(_translate("MainWindow", "Next part:"))
        self.lbl_last_council.setText(_translate("MainWindow", "00"))
        self.freq_box.setItemText(0, _translate("MainWindow", "Twice as often"))
        self.freq_box.setItemText(1, _translate("MainWindow", "Normal"))
        self.freq_box.setItemText(2, _translate("MainWindow", "1/2 as often"))
        self.freq_box.setItemText(3, _translate("MainWindow", "1/3 as often"))
        self.freq_box.setItemText(4, _translate("MainWindow", "1/4 as often"))
        self.label_5.setText(_translate("MainWindow", "Assigning next:"))
        self.next_council_box.setItemText(0, _translate("MainWindow", "0"))
        self.next_council_box.setItemText(1, _translate("MainWindow", "1"))
        self.next_council_box.setItemText(2, _translate("MainWindow", "2"))
        self.next_council_box.setItemText(3, _translate("MainWindow", "3"))
        self.next_council_box.setItemText(4, _translate("MainWindow", "4"))
        self.next_council_box.setItemText(5, _translate("MainWindow", "5"))
        self.next_council_box.setItemText(6, _translate("MainWindow", "6"))
        self.next_council_box.setItemText(7, _translate("MainWindow", "7"))
        self.next_council_box.setItemText(8, _translate("MainWindow", "8"))
        self.next_council_box.setItemText(9, _translate("MainWindow", "9"))
        self.next_council_box.setItemText(10, _translate("MainWindow", "10"))
        self.next_council_box.setItemText(11, _translate("MainWindow", "11"))
        self.next_council_box.setItemText(12, _translate("MainWindow", "12"))
        self.next_council_box.setItemText(13, _translate("MainWindow", "13"))
        self.next_council_box.setItemText(14, _translate("MainWindow", "14"))
        self.next_council_box.setItemText(15, _translate("MainWindow", "15"))
        self.next_council_box.setItemText(16, _translate("MainWindow", "16"))
        self.next_council_box.setItemText(17, _translate("MainWindow", "17"))
        self.next_council_box.setItemText(18, _translate("MainWindow", "18"))
        self.next_council_box.setItemText(19, _translate("MainWindow", "19"))
        self.next_council_box.setItemText(20, _translate("MainWindow", "20"))
        self.next_council_box.setItemText(21, _translate("MainWindow", "21"))
        self.next_council_box.setItemText(22, _translate("MainWindow", "22"))
        self.next_council_box.setItemText(23, _translate("MainWindow", "23"))
        self.next_council_box.setItemText(24, _translate("MainWindow", "24"))
        self.next_council_box.setItemText(25, _translate("MainWindow", "25"))
        self.next_council_box.setItemText(26, _translate("MainWindow", "26"))
        self.next_council_box.setItemText(27, _translate("MainWindow", "27"))
        self.next_council_box.setItemText(28, _translate("MainWindow", "28"))
        self.next_council_box.setItemText(29, _translate("MainWindow", "29"))
        self.next_council_box.setItemText(30, _translate("MainWindow", "30"))
        self.next_council_box.setItemText(31, _translate("MainWindow", "31"))
        self.next_council_box.setItemText(32, _translate("MainWindow", "32"))
        self.next_council_box.setItemText(33, _translate("MainWindow", "33"))
        self.next_council_box.setItemText(34, _translate("MainWindow", "34"))
        self.next_council_box.setItemText(35, _translate("MainWindow", "35"))
        self.next_council_box.setItemText(36, _translate("MainWindow", "36"))
        self.next_council_box.setItemText(37, _translate("MainWindow", "37"))
        self.next_council_box.setItemText(38, _translate("MainWindow", "38"))
        self.next_council_box.setItemText(39, _translate("MainWindow", "39"))
        self.next_council_box.setItemText(40, _translate("MainWindow", "40"))
        self.next_council_box.setItemText(41, _translate("MainWindow", "41"))
        self.next_council_box.setItemText(42, _translate("MainWindow", "42"))
        self.next_council_box.setItemText(43, _translate("MainWindow", "43"))
        self.next_council_box.setItemText(44, _translate("MainWindow", "44"))
        self.next_council_box.setItemText(45, _translate("MainWindow", "45"))
        self.next_council_box.setItemText(46, _translate("MainWindow", "46"))
        self.next_council_box.setItemText(47, _translate("MainWindow", "47"))
        self.next_council_box.setItemText(48, _translate("MainWindow", "48"))
        self.next_council_box.setItemText(49, _translate("MainWindow", "49"))
        self.next_council_box.setItemText(50, _translate("MainWindow", "50"))
        self.next_council_box.setItemText(51, _translate("MainWindow", "51"))
        self.next_council_box.setItemText(52, _translate("MainWindow", "52"))
        self.next_council_box.setItemText(53, _translate("MainWindow", "53"))
        self.lbl_next_council.setText(_translate("MainWindow", "00"))
        self.schedule.setTitle(_translate("MainWindow", "Schedule"))
        self.chk_slips_printed.setText(_translate("MainWindow", "Slips have been printed."))
        self.mtg_parts.setTitle(_translate("MainWindow", "Meeting Parts"))
        self.lbl_rv_hhold_pub.setText(_translate("MainWindow", "Publisher Name 3A"))
        self.lbl_hhold.setText(_translate("MainWindow", "Householder:"))
        self.assign_bs.setText(_translate("MainWindow", "Assign"))
        self.assign_rvh.setText(_translate("MainWindow", "Assign"))
        self.lbl_bs_cou.setText(_translate("MainWindow", "00"))
        self.assign_bsh.setText(_translate("MainWindow", "Assign"))
        self.lbl_bs_pub.setText(_translate("MainWindow", "Publisher Name 4"))
        self.lbl_bs.setText(_translate("MainWindow", "Bible Study:"))
        self.lbl_bs_hhold_pub.setText(_translate("MainWindow", "Publisher Name 4A"))
        self.label_18.setText(_translate("MainWindow", "Council"))
        self.lbl_fv.setText(_translate("MainWindow", "First Visit:"))
        self.lbl_fv_pub.setText(_translate("MainWindow", "Publisher Name 2"))
        self.lbl_read_cou.setText(_translate("MainWindow", "00"))
        self.assign_fv.setText(_translate("MainWindow", "Assign"))
        self.lbl_read_pub.setText(_translate("MainWindow", "Publisher Name 1"))
        self.assign_reading.setText(_translate("MainWindow", "Assign"))
        self.lbl_fv_cou.setText(_translate("MainWindow", "00"))
        self.label_15.setText(_translate("MainWindow", "Part"))
        self.lbl_fv_hhold.setText(_translate("MainWindow", "Householder:"))
        self.lvl_rv.setText(_translate("MainWindow", "Return Visit:"))
        self.lbl_rv_cou.setText(_translate("MainWindow", "00"))
        self.assign_rv.setText(_translate("MainWindow", "Assign"))
        self.lvl_rv_hhold.setText(_translate("MainWindow", "Householder:"))
        self.label_17.setText(_translate("MainWindow", "Publisher"))
        self.lbl_read.setText(_translate("MainWindow", "Reading:"))
        self.lbl_fv_hhold_pub.setText(_translate("MainWindow", "Publisher Name 2A"))
        self.assign_fvh.setText(_translate("MainWindow", "Assign"))
        self.lbl_rv_pub.setText(_translate("MainWindow", "Publisher Name 3"))
        self.label_28.setText(_translate("MainWindow", "Cancel"))
        self.btn_edit_list.setText(_translate("MainWindow", "Edit Publisher List"))
        self.btn_close.setText(_translate("MainWindow", "Close"))

